[project]
name = "pythonproject"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "ollama>=0.6.2",
    "recursivecharactertextsplitter>=0.1.0",
]
